fix: Remove fps attribute from pytubefix stream logging
BUG: AttributeError: 'Stream' object has no attribute 'fps'
FIX: Removed fps from stream logging (pytubefix.Stream doesn't have this attribute)